version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: northfish-db
    restart: always
    environment:
      POSTGRES_USER: northf_user
      POSTGRES_PASSWORD: "%KM041286)zz!"
      POSTGRES_DB: north_fish
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: northfish-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://northf_user:%25KM041286)zz!@db/north_fish"
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

volumes:
  postgres_data:
    external: true