from datetime import datetime

"""Consolidated initial migration

Revision ID: f42597e76a0d
Revises: 
Create Date: 2025-04-03 19:20:08.254034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42597e76a0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('permissions', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrators_email'), 'administrators', ['email'], unique=True)
    op.create_index(op.f('ix_administrators_id'), 'administrators', ['id'], unique=False)
    op.create_index(op.f('ix_administrators_username'), 'administrators', ['username'], unique=True)
    op.drop_index('ix_cart_id', table_name='cart')
    op.drop_table('cart')
    op.add_column('categories', sa.Column('parent_category_id', sa.Integer(), nullable=True))
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_index('ix_categories_slug', table_name='categories')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_category_id'], ['id'])
    op.drop_column('categories', 'slug')
    op.drop_column('orders', 'delivery_method')
    op.drop_column('orders', 'delivery_postal_code')
    op.drop_column('orders', 'delivery_city')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'comment')
    op.drop_column('orders', 'email')
    op.drop_column('orders', 'customer_name')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.drop_constraint('payments_order_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'])
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_products_name', table_name='products')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'image_url')
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.drop_constraint('shipments_order_id_fkey', 'shipments', type_='foreignkey')
    op.create_foreign_key(None, 'shipments', 'orders', ['order_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_phone', 'users', ['phone'], unique=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.create_foreign_key('shipments_order_id_fkey', 'shipments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('weight', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'stock_quantity')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_order_id_fkey', 'payments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.add_column('orders', sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('delivery_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('delivery_postal_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('delivery_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_index('ix_categories_slug', 'categories', ['slug'], unique=True)
    op.create_index('ix_categories_name', 'categories', ['name'], unique=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('categories', 'parent_category_id')
    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='cart_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='cart_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cart_pkey')
    )
    op.create_index('ix_cart_id', 'cart', ['id'], unique=False)
    op.drop_index(op.f('ix_administrators_username'), table_name='administrators')
    op.drop_index(op.f('ix_administrators_id'), table_name='administrators')
    op.drop_index(op.f('ix_administrators_email'), table_name='administrators')
    op.drop_table('administrators')
    # ### end Alembic commands ###
